spring:
    application:
        name: demoSpringData

    datasource:
        url: jdbc:sqlserver://localhost;databasename=ludo_db;encrypt=false
        username: sa
        password: "Pa$$w0rd"

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                ddl-auto: create
